-- =====================================================================
--  AIRLINE BOOKING SYSTEM  |  SQL Project
--  Dialect: PostgreSQL 14+
--  Sections:
--    1. Schema (DDL)          4. Views
--    2. Indexes               5. Analysis queries (joins, aggregates,
--    3. Sample data (DML)        subqueries, CTEs, window functions)
-- =====================================================================

DROP VIEW  IF EXISTS v_flight_details;
DROP TABLE IF EXISTS payments CASCADE;
DROP TABLE IF EXISTS bookings CASCADE;
DROP TABLE IF EXISTS flights CASCADE;
DROP TABLE IF EXISTS passengers CASCADE;
DROP TABLE IF EXISTS airports CASCADE;
DROP TABLE IF EXISTS airlines CASCADE;

-- ---------------------------------------------------------------------
-- 1. SCHEMA
-- ---------------------------------------------------------------------
CREATE TABLE airlines (
    airline_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(80) NOT NULL,
    iata_code    CHAR(2)     NOT NULL UNIQUE,
    country      VARCHAR(50) NOT NULL
);

CREATE TABLE airports (
    airport_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    iata_code    CHAR(3)     NOT NULL UNIQUE,
    name         VARCHAR(100) NOT NULL,
    city         VARCHAR(50) NOT NULL,
    country      VARCHAR(50) NOT NULL
);

CREATE TABLE flights (
    flight_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    flight_number  VARCHAR(10) NOT NULL,
    airline_id     INTEGER NOT NULL REFERENCES airlines(airline_id),
    origin_id      INTEGER NOT NULL REFERENCES airports(airport_id),
    destination_id INTEGER NOT NULL REFERENCES airports(airport_id),
    departure_time TIMESTAMP NOT NULL,
    arrival_time   TIMESTAMP NOT NULL,
    base_price     DECIMAL(10,2) NOT NULL CHECK (base_price > 0),
    total_seats    INTEGER NOT NULL CHECK (total_seats > 0),
    CHECK (origin_id <> destination_id),
    CHECK (arrival_time > departure_time)
);

CREATE TABLE passengers (
    passenger_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(50)  NOT NULL,
    last_name     VARCHAR(50)  NOT NULL,
    email         VARCHAR(100) NOT NULL UNIQUE,
    phone         VARCHAR(20),
    nationality   VARCHAR(50),
    date_of_birth DATE NOT NULL
);

CREATE TABLE bookings (
    booking_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    passenger_id  INTEGER NOT NULL REFERENCES passengers(passenger_id),
    flight_id     INTEGER NOT NULL REFERENCES flights(flight_id),
    booking_date  DATE NOT NULL,
    seat_number   VARCHAR(4) NOT NULL,
    travel_class  VARCHAR(10) NOT NULL CHECK (travel_class IN ('Economy','Business','First')),
    status        VARCHAR(10) NOT NULL CHECK (status IN ('Confirmed','Cancelled','Completed')),
    fare          DECIMAL(10,2) NOT NULL CHECK (fare >= 0),
    UNIQUE (flight_id, seat_number)            -- a seat can only be sold once per flight
);

CREATE TABLE payments (
    payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id    INTEGER NOT NULL REFERENCES bookings(booking_id),
    amount        DECIMAL(10,2) NOT NULL CHECK (amount >= 0),
    method        VARCHAR(15) NOT NULL CHECK (method IN ('Credit Card','Debit Card','UPI','Net Banking','PayPal')),
    status        VARCHAR(10) NOT NULL CHECK (status IN ('Paid','Pending','Failed','Refunded')),
    payment_date  DATE NOT NULL
);

-- ---------------------------------------------------------------------
-- 2. INDEXES (speed up the joins/filters used in the analysis below)
-- ---------------------------------------------------------------------
CREATE INDEX idx_flights_airline     ON flights(airline_id);
CREATE INDEX idx_flights_route       ON flights(origin_id, destination_id);
CREATE INDEX idx_bookings_passenger  ON bookings(passenger_id);
CREATE INDEX idx_bookings_flight     ON bookings(flight_id);
CREATE INDEX idx_bookings_date       ON bookings(booking_date);
CREATE INDEX idx_payments_booking    ON payments(booking_id);

-- ---------------------------------------------------------------------
-- 3. SAMPLE DATA
-- ---------------------------------------------------------------------
INSERT INTO airlines (airline_id, name, iata_code, country) VALUES
 (1,'Air India','AI','India'),
 (2,'IndiGo','6E','India'),
 (3,'Emirates','EK','UAE'),
 (4,'British Airways','BA','United Kingdom'),
 (5,'Singapore Airlines','SQ','Singapore'),
 (6,'SpiceJet','SG','India');   -- no flights booked: useful for LEFT JOIN demos

INSERT INTO airports (airport_id, iata_code, name, city, country) VALUES
 (1,'DEL','Indira Gandhi International','Delhi','India'),
 (2,'BOM','Chhatrapati Shivaji Maharaj International','Mumbai','India'),
 (3,'BLR','Kempegowda International','Bengaluru','India'),
 (4,'DXB','Dubai International','Dubai','UAE'),
 (5,'LHR','Heathrow','London','United Kingdom'),
 (6,'SIN','Changi','Singapore','Singapore'),
 (7,'JFK','John F. Kennedy International','New York','USA'),
 (8,'HYD','Rajiv Gandhi International','Hyderabad','India');

INSERT INTO flights (flight_id, flight_number, airline_id, origin_id, destination_id, departure_time, arrival_time, base_price, total_seats) VALUES
 (1 ,'AI101',1,1,5,'2026-01-10 02:00','2026-01-10 06:30',52000,250),
 (2 ,'6E202',2,3,1,'2026-01-12 06:00','2026-01-12 08:45', 6500,180),
 (3 ,'EK500',3,2,4,'2026-01-15 04:00','2026-01-15 06:00',24000,300),
 (4 ,'SQ423',5,3,6,'2026-02-03 23:30','2026-02-04 06:30',31000,280),
 (5 ,'BA138',4,5,3,'2026-02-08 21:00','2026-02-09 11:00',58000,240),
 (6 ,'AI202',1,2,1,'2026-02-14 07:00','2026-02-14 09:10', 7200,180),
 (7 ,'6E455',2,8,3,'2026-02-20 18:30','2026-02-20 19:50', 4200,180),
 (8 ,'EK202',3,4,7,'2026-03-05 08:30','2026-03-05 14:30',78000,350),
 (9 ,'AI144',1,1,7,'2026-03-12 01:30','2026-03-12 07:00',85000,300),
 (10,'SQ501',5,6,1,'2026-03-18 09:00','2026-03-18 12:30',36000,280),
 (11,'6E610',2,3,2,'2026-03-25 10:00','2026-03-25 11:45', 5500,180),
 (12,'EK516',3,4,3,'2026-04-02 03:00','2026-04-02 08:00',21000,300),
 (13,'BA142',4,3,5,'2026-04-10 02:30','2026-04-10 08:30',56000,240),
 (14,'AI505',1,3,4,'2026-04-18 05:00','2026-04-18 07:30',23000,200);

INSERT INTO passengers (passenger_id, first_name, last_name, email, phone, nationality, date_of_birth) VALUES
 (1 ,'Aarav','Sharma','aarav.sharma@example.com','+91-9800000001','Indian','1990-05-14'),
 (2 ,'Priya','Nair','priya.nair@example.com','+91-9800000002','Indian','1985-11-02'),
 (3 ,'Rohan','Mehta','rohan.mehta@example.com','+91-9800000003','Indian','1993-07-21'),
 (4 ,'Emily','Clarke','emily.clarke@example.com','+44-7700000004','British','1988-03-30'),
 (5 ,'Liam','Tan','liam.tan@example.com','+65-8100000005','Singaporean','1995-09-09'),
 (6 ,'Fatima','Al-Sayed','fatima.alsayed@example.com','+971-500000006','Emirati','1991-12-25'),
 (7 ,'Kavya','Reddy','kavya.reddy@example.com','+91-9800000007','Indian','1998-01-17'),
 (8 ,'Daniel','Brooks','daniel.brooks@example.com','+1-2120000008','American','1980-06-05'),
 (9 ,'Ananya','Iyer','ananya.iyer@example.com','+91-9800000009','Indian','2001-08-19'),
 (10,'Omar','Khan','omar.khan@example.com','+971-500000010','Pakistani','1987-04-11'),
 (11,'Sofia','Rossi','sofia.rossi@example.com','+39-3300000011','Italian','1992-10-28'),
 (12,'Vikram','Singh','vikram.singh@example.com','+91-9800000012','Indian','1979-02-08');  -- only has a cancelled booking: LEFT JOIN demo

INSERT INTO bookings (booking_id, passenger_id, flight_id, booking_date, seat_number, travel_class, status, fare) VALUES
 (1 ,1 ,1 ,'2025-12-01','12A','Economy','Completed', 52000),
 (2 ,2 ,1 ,'2025-12-05','12B','Economy','Completed', 52000),
 (3 ,4 ,1 ,'2025-12-10','2A' ,'Business','Completed',104000),
 (4 ,3 ,2 ,'2026-01-02','5C' ,'Economy','Completed',  6500),
 (5 ,7 ,2 ,'2026-01-04','5D' ,'Economy','Cancelled',  6500),
 (6 ,6 ,3 ,'2026-01-05','8A' ,'Economy','Completed', 24000),
 (7 ,10,3 ,'2026-01-06','1A' ,'First'  ,'Completed', 60000),
 (8 ,1 ,4 ,'2026-01-15','15F','Economy','Completed', 31000),
 (9 ,5 ,4 ,'2026-01-18','3A' ,'Business','Completed', 62000),
 (10,9 ,4 ,'2026-01-20','15E','Economy','Completed', 31000),
 (11,4 ,5 ,'2026-01-22','20A','Economy','Completed', 58000),
 (12,8 ,5 ,'2026-01-25','2B' ,'Business','Completed',116000),
 (13,2 ,6 ,'2026-01-28','10A','Economy','Completed',  7200),
 (14,3 ,6 ,'2026-02-01','10B','Economy','Completed',  7200),
 (15,12,6 ,'2026-02-02','1C' ,'Business','Cancelled', 14400),
 (16,7 ,7 ,'2026-02-05','7A' ,'Economy','Completed',  4200),
 (17,9 ,7 ,'2026-02-06','7B' ,'Economy','Completed',  4200),
 (18,8 ,8 ,'2026-02-10','30A','Economy','Completed', 78000),
 (19,11,8 ,'2026-02-12','2A' ,'First'  ,'Completed',195000),
 (20,6 ,8 ,'2026-02-14','30B','Economy','Completed', 78000),
 (21,1 ,9 ,'2026-02-18','25C','Economy','Completed', 85000),
 (22,2 ,9 ,'2026-02-20','25D','Economy','Cancelled', 85000),
 (23,5 ,10,'2026-02-25','14A','Economy','Completed', 36000),
 (24,10,10,'2026-02-26','4A' ,'Business','Completed', 72000),
 (25,3 ,11,'2026-03-01','9A' ,'Economy','Completed',  5500),
 (26,7 ,11,'2026-03-02','9B' ,'Economy','Completed',  5500),
 (27,9 ,12,'2026-03-05','18A','Economy','Completed', 21000),
 (28,4 ,13,'2026-03-10','22A','Economy','Confirmed', 56000),
 (29,1 ,13,'2026-03-12','3C' ,'Business','Confirmed',112000),
 (30,2 ,14,'2026-03-15','11A','Economy','Confirmed', 23000),
 (31,6 ,14,'2026-03-16','11B','Economy','Confirmed', 23000),
 (32,8 ,12,'2026-03-18','2C' ,'Business','Confirmed', 42000);

-- Payments are derived from booking status (one payment per booking):
--   Completed -> Paid | Confirmed -> Paid (except a few Pending) | Cancelled -> Refunded
INSERT INTO payments (payment_id, booking_id, amount, method, status, payment_date)
SELECT b.booking_id,
       b.booking_id,
       b.fare,
       CASE b.booking_id % 5
            WHEN 0 THEN 'Credit Card'
            WHEN 1 THEN 'UPI'
            WHEN 2 THEN 'Debit Card'
            WHEN 3 THEN 'Net Banking'
            ELSE 'PayPal' END,
       CASE WHEN b.status = 'Cancelled'            THEN 'Refunded'
            WHEN b.booking_id IN (31, 32)          THEN 'Pending'
            ELSE 'Paid' END,
       b.booking_date
FROM bookings b;

-- Resync identity counters because sample rows were inserted with explicit IDs
SELECT setval(pg_get_serial_sequence('airlines','airline_id'),     (SELECT MAX(airline_id)   FROM airlines));
SELECT setval(pg_get_serial_sequence('airports','airport_id'),     (SELECT MAX(airport_id)   FROM airports));
SELECT setval(pg_get_serial_sequence('flights','flight_id'),       (SELECT MAX(flight_id)    FROM flights));
SELECT setval(pg_get_serial_sequence('passengers','passenger_id'), (SELECT MAX(passenger_id) FROM passengers));
SELECT setval(pg_get_serial_sequence('bookings','booking_id'),     (SELECT MAX(booking_id)   FROM bookings));
SELECT setval(pg_get_serial_sequence('payments','payment_id'),     (SELECT MAX(payment_id)   FROM payments));

-- ---------------------------------------------------------------------
-- 4. VIEW: one row per flight with airline + route (reused below)
-- ---------------------------------------------------------------------
CREATE VIEW v_flight_details AS
SELECT f.flight_id,
       f.flight_number,
       a.name          AS airline,
       o.city          AS origin_city,
       d.city          AS destination_city,
       f.departure_time,
       f.arrival_time,
       f.base_price,
       f.total_seats
FROM flights  f
JOIN airlines a ON a.airline_id = f.airline_id
JOIN airports o ON o.airport_id = f.origin_id
JOIN airports d ON d.airport_id = f.destination_id;

-- ---------------------------------------------------------------------
-- 5. ANALYSIS QUERIES
-- ---------------------------------------------------------------------

-- Q1. Flight details (JOIN via view)
SELECT flight_number, airline, origin_city, destination_city, departure_time, base_price
FROM v_flight_details
ORDER BY departure_time;

-- Q2. Full booking report: passenger, flight, route, class, status (multi-table JOIN)
SELECT b.booking_id,
       p.first_name || ' ' || p.last_name AS passenger,
       fd.flight_number,
       fd.origin_city || ' -> ' || fd.destination_city AS route,
       b.travel_class, b.status, b.fare
FROM bookings b
JOIN passengers p         ON p.passenger_id = b.passenger_id
JOIN v_flight_details fd  ON fd.flight_id   = b.flight_id
ORDER BY b.booking_id;

-- Q3. Total revenue (only money actually retained: Paid payments)
SELECT SUM(amount) AS total_revenue
FROM payments
WHERE status = 'Paid';

-- Q4. Revenue by airline (aggregation + JOINs)
SELECT a.name AS airline,
       COUNT(DISTINCT b.booking_id) AS paid_bookings,
       SUM(pay.amount)              AS revenue
FROM payments pay
JOIN bookings b ON b.booking_id = pay.booking_id
JOIN flights  f ON f.flight_id  = b.flight_id
JOIN airlines a ON a.airline_id = f.airline_id
WHERE pay.status = 'Paid'
GROUP BY a.airline_id, a.name
ORDER BY revenue DESC;

-- Q5. Most popular destinations (excluding cancelled bookings)
SELECT d.city AS destination, d.country,
       COUNT(*) AS bookings
FROM bookings b
JOIN flights  f ON f.flight_id   = b.flight_id
JOIN airports d ON d.airport_id  = f.destination_id
WHERE b.status <> 'Cancelled'
GROUP BY d.airport_id, d.city, d.country
ORDER BY bookings DESC, destination
LIMIT 5;

-- Q6. Monthly booking trend
SELECT TO_CHAR(booking_date, 'YYYY-MM') AS month,
       COUNT(*)  AS bookings,
       SUM(fare) AS booked_value
FROM bookings
GROUP BY month
ORDER BY month;

-- Q7. Month-over-month growth in bookings (CTE + window function LAG)
WITH monthly AS (
    SELECT TO_CHAR(booking_date, 'YYYY-MM') AS month, COUNT(*) AS bookings
    FROM bookings
    GROUP BY month
)
SELECT month,
       bookings,
       LAG(bookings) OVER (ORDER BY month) AS prev_month,
       ROUND(100.0 * (bookings - LAG(bookings) OVER (ORDER BY month))
                   / LAG(bookings) OVER (ORDER BY month), 1) AS growth_pct
FROM monthly;

-- Q8. Seat occupancy per flight (aggregation + arithmetic)
SELECT fd.flight_number,
       fd.origin_city || ' -> ' || fd.destination_city AS route,
       fd.total_seats,
       COUNT(b.booking_id) AS seats_sold,
       ROUND(100.0 * COUNT(b.booking_id) / fd.total_seats, 2) AS occupancy_pct
FROM v_flight_details fd
LEFT JOIN bookings b ON b.flight_id = fd.flight_id AND b.status <> 'Cancelled'
GROUP BY fd.flight_id, fd.flight_number, fd.origin_city, fd.destination_city, fd.total_seats
ORDER BY occupancy_pct DESC;

-- Q9. Passengers with no active trips: never booked, or only cancelled (LEFT JOIN ... IS NULL)
SELECT p.passenger_id, p.first_name, p.last_name, p.email
FROM passengers p
LEFT JOIN bookings b ON b.passenger_id = p.passenger_id AND b.status <> 'Cancelled'
WHERE b.booking_id IS NULL;

-- Q10. Airlines with no flights that have bookings (subquery with NOT IN)
SELECT name
FROM airlines
WHERE airline_id NOT IN (
    SELECT DISTINCT f.airline_id
    FROM flights f
    JOIN bookings b ON b.flight_id = f.flight_id
);

-- Q11. Passengers who spent more than the average passenger (subquery in HAVING)
SELECT p.first_name || ' ' || p.last_name AS passenger,
       SUM(pay.amount) AS total_spent
FROM passengers p
JOIN bookings b    ON b.passenger_id = p.passenger_id
JOIN payments pay  ON pay.booking_id = b.booking_id
WHERE pay.status = 'Paid'
GROUP BY p.passenger_id, p.first_name, p.last_name
HAVING SUM(pay.amount) > (
    SELECT AVG(per_passenger)
    FROM (
        SELECT SUM(pay2.amount) AS per_passenger
        FROM bookings b2
        JOIN payments pay2 ON pay2.booking_id = b2.booking_id
        WHERE pay2.status = 'Paid'
        GROUP BY b2.passenger_id
    ) AS totals
)
ORDER BY total_spent DESC;

-- Q12. Frequent flyers: passengers with 3+ non-cancelled bookings
SELECT p.first_name || ' ' || p.last_name AS passenger,
       COUNT(*) AS trips
FROM passengers p
JOIN bookings b ON b.passenger_id = p.passenger_id
WHERE b.status <> 'Cancelled'
GROUP BY p.passenger_id, p.first_name, p.last_name
HAVING COUNT(*) >= 3
ORDER BY trips DESC;

-- Q13. Cancellation rate by airline
SELECT a.name AS airline,
       COUNT(*) AS total_bookings,
       SUM(CASE WHEN b.status = 'Cancelled' THEN 1 ELSE 0 END) AS cancelled,
       ROUND(100.0 * SUM(CASE WHEN b.status = 'Cancelled' THEN 1 ELSE 0 END) / COUNT(*), 1) AS cancel_rate_pct
FROM bookings b
JOIN flights  f ON f.flight_id  = b.flight_id
JOIN airlines a ON a.airline_id = f.airline_id
GROUP BY a.airline_id, a.name
ORDER BY cancel_rate_pct DESC;

-- Q14. Revenue and share by travel class
SELECT b.travel_class,
       COUNT(*) AS bookings,
       SUM(pay.amount) AS revenue,
       ROUND(100.0 * SUM(pay.amount) / SUM(SUM(pay.amount)) OVER (), 1) AS revenue_share_pct
FROM bookings b
JOIN payments pay ON pay.booking_id = b.booking_id
WHERE pay.status = 'Paid'
GROUP BY b.travel_class
ORDER BY revenue DESC;

-- Q15. Payment method popularity and status breakdown
SELECT method,
       COUNT(*) AS payments,
       SUM(CASE WHEN status = 'Paid'     THEN 1 ELSE 0 END) AS paid,
       SUM(CASE WHEN status = 'Pending'  THEN 1 ELSE 0 END) AS pending,
       SUM(CASE WHEN status = 'Refunded' THEN 1 ELSE 0 END) AS refunded
FROM payments
GROUP BY method
ORDER BY payments DESC;

-- Q16. Top-earning route per airline (window function RANK in a CTE)
WITH route_rev AS (
    SELECT a.name AS airline,
           fd.origin_city || ' -> ' || fd.destination_city AS route,
           SUM(pay.amount) AS revenue
    FROM payments pay
    JOIN bookings b        ON b.booking_id  = pay.booking_id
    JOIN v_flight_details fd ON fd.flight_id = b.flight_id
    JOIN flights f         ON f.flight_id   = fd.flight_id
    JOIN airlines a        ON a.airline_id  = f.airline_id
    WHERE pay.status = 'Paid'
    GROUP BY a.name, fd.origin_city, fd.destination_city
),
ranked AS (
    SELECT *, RANK() OVER (PARTITION BY airline ORDER BY revenue DESC) AS rnk
    FROM route_rev
)
SELECT airline, route, revenue
FROM ranked
WHERE rnk = 1
ORDER BY revenue DESC;

-- Q17. Data-quality check: bookings whose payment amount doesn't match the fare
SELECT b.booking_id, b.fare, pay.amount
FROM bookings b
JOIN payments pay ON pay.booking_id = b.booking_id
WHERE pay.amount <> b.fare;

-- Q18. Pending payments needing follow-up (with passenger contact)
SELECT p.first_name || ' ' || p.last_name AS passenger, p.email, pay.amount, pay.payment_date
FROM payments pay
JOIN bookings b   ON b.booking_id   = pay.booking_id
JOIN passengers p ON p.passenger_id = b.passenger_id
WHERE pay.status = 'Pending';

